/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import cola.Cola;
import data.Cliente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import modelo.Cajero;

/**
 *
 * @author montero
 */
public class UI_Cajero extends javax.swing.JFrame {

    private Cola<Cliente> colaClientes;
    private LinkedList<Cajero> cajeros;
    private Timer timer;
    private int clientesAtendidos;
    private final int[] clientesPorCajero;
    private final Duration[] tiempoTotalPorCajero;
    private final Random random;
    private final DefaultTableModel tableModel;

    /**
     * Creates new form IU_Cajero
     */
    public UI_Cajero() {
        initComponents();
        colaClientes = new Cola<>();
        cajeros = new LinkedList<>();
        for (int i = 0; i < 4; i++) {
            cajeros.add(new Cajero());
        }
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                hacerQueTodoFuncione();
            }
        });
        timer.setRepeats(true);
        timer.start();
        while (true) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Error "+e.toString());
            }
        }
       

//        tableModel = (DefaultTableModel) jTable1.getModel();
    }

    public void  hacerQueTodoFuncione(){
        crearClientes();
        revisarCajeros();
    }
    public void crearClientes(){
        
    }
    
    public void revisarCajeros(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Terminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Caja", "Estado", "Numero clientes", "Tiempo Servicio"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        timer = new Timer(1000, (ActionEvent e) -> {
            generarCliente();
            atenderClientes();
            actualizarInterfaz();
        });
        timer.start();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        timer.stop();
        mostrarResultados();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void generarCliente() {
//
//        int idCliente = clientesAtendidos + 1;
//        int monto = 100 + random.nextInt(900);
//        Duration tiempoServicio = Duration.ofSeconds(1 + random.nextInt(10));
//        int transaccion = random.nextInt(3);
//
//        Cajero cliente = new Cajero(0, idCliente, monto, tiempoServicio, transaccion);
//        colaClientes.encolar(cliente);
//        clientesAtendidos++;
    }

    private void atenderClientes() {
//        for (int i = 0; i < cajeros.size(); i++) {
//            if (cajeros.get(i).isEmpty() && !colaClientes.estaVacia()) {
//                Cajero cliente = colaClientes.desencolar();
//                cajeros.get(i).add(cliente);
//                clientesPorCajero[i]++;
//                tiempoTotalPorCajero[i] = tiempoTotalPorCajero[i].plus(cliente.getTiemposervicio());
//            }
//        }
    }

    private void actualizarInterfaz() {

//        textArea1.setText("");
//        for (int i = 0; i < cajeros.size(); i++) {
//            textArea1.append("Cajero " + (i + 1) + ":\n");
//            textArea1.append("  Clientes atendidos: " + clientesPorCajero[i] + "\n");
//            if (!cajeros.get(i).isEmpty()) {
//                Cajero clienteActual = cajeros.get(i).get(cajeros.get(i).size() - 1);
//                textArea1.append("  Cliente actual: " + clienteActual.getIdcliente() + "\n");
//                textArea1.append("  Monto: " + clienteActual.getMonto() + "\n");
//                textArea1.append("  Tiempo restante: " + clienteActual.getTiemposervicio().toSeconds() + " segundos\n");
//            } else {
//                textArea1.append("  Libre\n");
//            }
//        }
    }

    private void mostrarResultados() {

        textArea1.append("\n--- Resultados Finales ---\n");
        for (int i = 0; i < cajeros.size(); i++) {
            textArea1.append("Cajero " + (i + 1) + ":\n");
            textArea1.append("  Clientes atendidos: " + clientesPorCajero[i] + "\n");
            textArea1.append("  Tiempo total de servicio: " + tiempoTotalPorCajero[i].toSeconds() + " Segundos\n");
            textArea1.append("  Tiempo promedio por transacción: " + tiempoTotalPorCajero[i].dividedBy(clientesPorCajero[i]).toSeconds() + " segundos\n");
        }
        textArea1.append("Clientes en cola sin atender: " + colaClientes.toString() + "\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UI_Cajero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
